#base "base/classloadoutpanel.res"

"Resource/UI/FullLoadoutPanel.res"
{
	"PresetsExplanation"	{	"xpos"	"9999"	"visible"	"0"	"enabled"	"0"	}
	"TauntsExplanation"		{	"xpos"	"9999"	"visible"	"0"	"enabled"	"0"	}
	"ToggleToRED"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"ToggleToRED"
		"xpos"										"c122"
		"ypos"										"c-47"
		"zpos"										"12"
		"wide"										"25"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"#TF_ScoreBoard_Red"
		"textAlignment"								"center"
		"scaleImage"								"1"
		"Command"									"sv_cheats 1; r_skin 0"
		"paintborder"								"0"
		"paintbackground"							"1"
		"paintbackgroundtype"						"2"
		"fgcolor"									"TanLight"
		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override"					"TanLight"
		"selectedFgColor_override" 					"TanLight"
		
		"bgcolor"									"189 59 60 255"
		"defaultBgColor_override" 					"189 59 60 255"
		"armedBgColor_override" 					"169 59 60 255"
		"depressedBgColor_override" 				"189 59 60 255"
		"selectedBgColor_override" 					"189 59 60 255"
	}
	
	"ToggleToBLU"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"ToggleToBLU"
		"xpos"										"c122"
		"ypos"										"c-32"
		"zpos"										"12"
		"wide"										"25"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"#TF_ScoreBoard_Blue"
		"textAlignment"								"center"
		"scaleImage"								"1"
		"Command"									"sv_cheats 1; r_skin 1"
		"paintborder"								"0"
		"paintbackground"							"1"
		"paintbackgroundtype"						"2"
		"fgcolor"									"TanLight"
		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
		"selectedFgColor_override" 					"TanLight"
		
		"bgcolor_override"							"91 122 140 255"
		"defaultBgColor_override" 					"91 122 140 255"
		"armedBgColor_override" 					"71 102 120 255"
		"depressedBgColor_override" 				"91 122 140 255"
		"selectedBgColor_override" 					"91 122 140 255"
	}
	
	"CharacterLoadoutButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"CharacterLoadoutButton"
		"xpos"										"c-25"
		"ypos"										"c90"
		"zpos"										"2"
		"wide"										"25"
		"tall"										"25"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"center"
		"labeltext"									"P"
		"font"										"m0reSymbols"
		"Command"									"characterloadout"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"

		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
	}

	"TauntLoadoutButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"TauntLoadoutButton"
		"xpos"										"c2"
		"ypos"										"c90"
		"zpos"										"2"
		"wide"										"25"
		"tall"										"25"
		"visible"									"1"
		"enabled"									"1"
		"textAlignment"								"center"
		"labeltext"									"Q"
		"font"										"m0reSymbols"
		"Command"									"tauntloadout"
		"sound_depressed"							"UI/buttonclick.wav"
		"sound_released"							"UI/buttonclickrelease.wav"

		"defaultFgColor_override" 					"TanLight"
		"armedFgColor_override" 					"TanLight"
		"depressedFgColor_override" 				"TanLight"
	}	
}
